### ISSUE TITLE
启动失败,bean定义无法被覆盖

### ISSUE THREAD

**Issue by tmaerd** [wujiuye/easymulti-datasource-spring-boot-starter#28]
The bean 'org.springframework.transaction.config.internalTransactionAdvisor', defined in class path resource [org/springframework/transaction/annotation/ProxyTransactionManagementConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/github/wujiuye/datasource/tx/TransactionAutoConfig.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by wujiuye** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wujiuye** [comment]
请不要使用@EnableTransactionManagement注解，或者exclude一下ProxyTransactionManagementConfiguration.class这个配置类。
